Repository ISISComputingGroup/CAENHVAsyn, pull requests merged in 2021-06, with the labels that each got.

#4 Fix getting binary params
  CAENHVAsynApp/src/drvCAENHVAsyn.cpp
Labels: size/S

#5 Only trigger monitors on string change
  CAENHVAsynApp/Db/stringin.template
Labels: size/XS

#3 Ticket6442 handling of return values
  CAENHVAsynApp/src/board.cpp
  CAENHVAsynApp/src/board_parameter.cpp
  CAENHVAsynApp/src/board_parameter.h
  CAENHVAsynApp/src/channel.cpp
  CAENHVAsynApp/src/channel_parameter.cpp
  CAENHVAsynApp/src/channel_parameter.h
  CAENHVAsynApp/src/common.cpp
  CAENHVAsynApp/src/common.h
  CAENHVAsynApp/src/crate.cpp
Labels: size/L

#2 Add caen sim
  CAENHVAsynApp/src/CAENHVWrapper_sim.cpp
  CAENHVAsynApp/src/Makefile
  CAENHVWrapper/CAENHVControlSw_REV1.pdf
  CAENHVWrapper/CAENHVWrapperReadme.txt
  CAENHVWrapper/CAENHVWrapperReleaseNotes.txt
  CAENHVWrapper/CAEN_License_Agreement.txt
  CAENHVWrapper/HV Wrapper_REV10.pdf
  CAENHVWrapper/HV Wrapper_REV7.pdf
  CAENHVWrapper/dll/win32/CAENHVWrapper.dll
  CAENHVWrapper/dll/win32/HSCAENETLib.dll
  CAENHVWrapper/dll/win64/CAENHVWrapper.dll
  CAENHVWrapper/dll/win64/HSCAENETLib.dll
  CAENHVWrapper/include/CAENHVWrapper.h
  CAENHVWrapper/include/caenhvoslib.h
  CAENHVWrapper/lib/linux-x86/hscaenetlib.so.1.7
  CAENHVWrapper/lib/linux-x86/libcaenhvwrapper.so
  CAENHVWrapper/lib/linux-x86/libcaenhvwrapper.so.6.0
  CAENHVWrapper/lib/linux-x86/libhscaenetlib.so
  CAENHVWrapper/lib/linux-x86_64-static/hscaenetlib.so.1.7
  CAENHVWrapper/lib/linux-x86_64-static/libcaenhvwrapper.so
  CAENHVWrapper/lib/linux-x86_64-static/libcaenhvwrapper.so.6.0
  CAENHVWrapper/lib/linux-x86_64-static/libhscaenet.so
  CAENHVWrapper/lib/linux-x86_64-static/libhscaenetlib.so
  CAENHVWrapper/lib/linux-x86_64/hscaenetlib.so.1.7
  CAENHVWrapper/lib/linux-x86_64/libcaenhvwrapper.so
  CAENHVWrapper/lib/linux-x86_64/libcaenhvwrapper.so.6.0
  CAENHVWrapper/lib/linux-x86_64/libhscaenet.so
  CAENHVWrapper/lib/linux-x86_64/libhscaenetlib.so
  CAENHVWrapper/lib/win32/CAENHVWrapper.lib
  CAENHVWrapper/lib/win64/CAENHVWrapper.lib
  configure/CONFIG_SITE.local
Labels: size/L
